### ISSUE TITLE
Demos not working

### ISSUE THREAD

**Issue by snarlynarwhal** [f15gdsy/2D-Light-of-Sight-Unity#3]
Hey, I noticed the demos look awesome, but when I attempted to open the demo scenes in engine, they did now work. I am using Unity 4.6.1. Basically, the scene opens, but no lighting effects / shadows. Am I supposed to do anything for demos to work or something?

**Comment by f15gdsy** [comment]
Hi, thanks for the question :) 
You don't need to setup extra things to try the demo. I just tried on another PC running Unity 4.5, which is ok.
Did you open the scene in an existing project, or did you open it in a new project? As the lighting / shadow effects need to work with layers in Unity, so if the layers used in demo are messed up with the layers in the existing project, it may not work. So if it's the reason, I recommend to use a new project to open the scene.
Hope it helps!

**Comment by snarlynarwhal** [comment]
Thanks for the speedy reply! I figured the issue was on my behalf hah. So you were correct, it automatically assigned the game object "Container - Obstacles" to one of my custom layers. By default (in your demo scene), the layer is blank. How is this possible? I cannot find a way to assign a blank or empty layer to a game object. Also, do they have to be blank? Can I create another custom layer that works with the lighting? I apologize for the plethora of questions xd

**Comment by f15gdsy** [comment]
Actually, it dont need to be blank, and should not be too. You can create and assign your own layers to it. 
Why it's blank in the demo is because the layer information was not put inside the example folder, so the scene just remember the index of the layer, but it doesn't know the name of the layer ;p

**Comment by snarlynarwhal** [comment]
Ahhh, I see! Thank you very much for your help! :)
