### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by NaakkaDev** [f15gdsy/2D-Light-of-Sight-Unity#5]
Hey!

You have made an awesome LoS plugin! I noticed that the README could be a bit more "clear", the Tips & Tricks section to be precise. Number 3. is a lie, even worse than the cake, and the number 6. should be either number 1. or  its own heading/title! :) 

Took me a couple hours to actually notice that I CAN use Box Collider 2D, etc.

**Comment by f15gdsy** [comment]
Thanks! I didn't notice it when I updated the readme.
I fixed it just now. Thanks again!
