### ISSUE TITLE
Los event trigger in 2D

### ISSUE THREAD

**Issue by bazuker** [f15gdsy/2D-Light-of-Sight-Unity#9]
Triggers do not really work in 2D mode. I was not able to use LOS event trigger in 2D physics mode. It basically does not recognize the event. Triggers only works with 3D physics. I really need to use 2D physics system. Any suggestions?

**Comment by dillyo09** [comment]
In the LOSEventSource you would want to change the RaycastHit to a RaycastHit2D in the process method.
